// Generated by CIRCT firtool-1.62.0
// external module PlaceHolder

module Cluster(
  input        I_N_IAct_0_pl,
               I_N_IAct_1_pl,
               I_N_IAct_2_pl,
               I_N_Psum_0_pl,
               I_N_Psum_1_pl,
               I_N_Psum_2_pl,
               I_S_IAct_0_pl,
               I_S_IAct_1_pl,
               I_S_IAct_2_pl,
               I_S_Psum_0_pl,
               I_S_Psum_1_pl,
               I_S_Psum_2_pl,
               I_W_IAct_0_pl,
               I_W_IAct_1_pl,
               I_W_IAct_2_pl,
               I_W_Weight_0_pl,
               I_W_Weight_1_pl,
               I_W_Weight_2_pl,
               I_E_IAct_0_pl,
               I_E_IAct_1_pl,
               I_E_IAct_2_pl,
               I_E_Weight_0_pl,
               I_E_Weight_1_pl,
               I_E_Weight_2_pl,
  output       O_N_IAct_0_pl,
               O_N_IAct_1_pl,
               O_N_IAct_2_pl,
               O_N_Psum_0_pl,
               O_N_Psum_1_pl,
               O_N_Psum_2_pl,
               O_S_IAct_0_pl,
               O_S_IAct_1_pl,
               O_S_IAct_2_pl,
               O_S_Psum_0_pl,
               O_S_Psum_1_pl,
               O_S_Psum_2_pl,
               O_W_IAct_0_pl,
               O_W_IAct_1_pl,
               O_W_IAct_2_pl,
               O_W_Weight_0_pl,
               O_W_Weight_1_pl,
               O_W_Weight_2_pl,
               O_E_IAct_0_pl,
               O_E_IAct_1_pl,
               O_E_IAct_2_pl,
               O_E_Weight_0_pl,
               O_E_Weight_1_pl,
               O_E_Weight_2_pl,
  input  [1:0] io_Mode
);

  PlaceHolder pl (
    .I_N_IAct_0_pl   (I_N_IAct_0_pl),
    .I_N_IAct_1_pl   (I_N_IAct_1_pl),
    .I_N_IAct_2_pl   (I_N_IAct_2_pl),
    .I_N_Psum_0_pl   (I_N_Psum_0_pl),
    .I_N_Psum_1_pl   (I_N_Psum_1_pl),
    .I_N_Psum_2_pl   (I_N_Psum_2_pl),
    .I_S_IAct_0_pl   (I_S_IAct_0_pl),
    .I_S_IAct_1_pl   (I_S_IAct_1_pl),
    .I_S_IAct_2_pl   (I_S_IAct_2_pl),
    .I_S_Psum_0_pl   (I_S_Psum_0_pl),
    .I_S_Psum_1_pl   (I_S_Psum_1_pl),
    .I_S_Psum_2_pl   (I_S_Psum_2_pl),
    .I_W_IAct_0_pl   (I_W_IAct_0_pl),
    .I_W_IAct_1_pl   (I_W_IAct_1_pl),
    .I_W_IAct_2_pl   (I_W_IAct_2_pl),
    .I_W_Weight_0_pl (I_W_Weight_0_pl),
    .I_W_Weight_1_pl (I_W_Weight_1_pl),
    .I_W_Weight_2_pl (I_W_Weight_2_pl),
    .I_E_IAct_0_pl   (I_E_IAct_0_pl),
    .I_E_IAct_1_pl   (I_E_IAct_1_pl),
    .I_E_IAct_2_pl   (I_E_IAct_2_pl),
    .I_E_Weight_0_pl (I_E_Weight_0_pl),
    .I_E_Weight_1_pl (I_E_Weight_1_pl),
    .I_E_Weight_2_pl (I_E_Weight_2_pl),
    .O_N_IAct_0_pl   (O_N_IAct_0_pl),
    .O_N_IAct_1_pl   (O_N_IAct_1_pl),
    .O_N_IAct_2_pl   (O_N_IAct_2_pl),
    .O_N_Psum_0_pl   (O_N_Psum_0_pl),
    .O_N_Psum_1_pl   (O_N_Psum_1_pl),
    .O_N_Psum_2_pl   (O_N_Psum_2_pl),
    .O_S_IAct_0_pl   (O_S_IAct_0_pl),
    .O_S_IAct_1_pl   (O_S_IAct_1_pl),
    .O_S_IAct_2_pl   (O_S_IAct_2_pl),
    .O_S_Psum_0_pl   (O_S_Psum_0_pl),
    .O_S_Psum_1_pl   (O_S_Psum_1_pl),
    .O_S_Psum_2_pl   (O_S_Psum_2_pl),
    .O_W_IAct_0_pl   (O_W_IAct_0_pl),
    .O_W_IAct_1_pl   (O_W_IAct_1_pl),
    .O_W_IAct_2_pl   (O_W_IAct_2_pl),
    .O_W_Weight_0_pl (O_W_Weight_0_pl),
    .O_W_Weight_1_pl (O_W_Weight_1_pl),
    .O_W_Weight_2_pl (O_W_Weight_2_pl),
    .O_E_IAct_0_pl   (O_E_IAct_0_pl),
    .O_E_IAct_1_pl   (O_E_IAct_1_pl),
    .O_E_IAct_2_pl   (O_E_IAct_2_pl),
    .O_E_Weight_0_pl (O_E_Weight_0_pl),
    .O_E_Weight_1_pl (O_E_Weight_1_pl),
    .O_E_Weight_2_pl (O_E_Weight_2_pl),
    .Mode            (io_Mode)
  );
endmodule

module ScanChain(
  input        clock,
               reset,
               io_in,
  output [7:0] io_out
);

  reg [7:0] Chain;
  always @(posedge clock) begin
    if (reset)
      Chain <= 8'h0;
    else
      Chain <= {io_in, Chain[7:1]};
  end // always @(posedge)
  assign io_out = Chain;
endmodule

module NoC(
  input clock,
        reset,
        io_ModeScanChain
);

  wire [7:0] _ModeScanChain_u_io_out;
  wire       _ClusterArray_1_1_O_N_IAct_0_pl;
  wire       _ClusterArray_1_1_O_N_IAct_1_pl;
  wire       _ClusterArray_1_1_O_N_IAct_2_pl;
  wire       _ClusterArray_1_1_O_N_Psum_0_pl;
  wire       _ClusterArray_1_1_O_N_Psum_1_pl;
  wire       _ClusterArray_1_1_O_N_Psum_2_pl;
  wire       _ClusterArray_1_1_O_W_IAct_0_pl;
  wire       _ClusterArray_1_1_O_W_IAct_1_pl;
  wire       _ClusterArray_1_1_O_W_IAct_2_pl;
  wire       _ClusterArray_1_1_O_W_Weight_0_pl;
  wire       _ClusterArray_1_1_O_W_Weight_1_pl;
  wire       _ClusterArray_1_1_O_W_Weight_2_pl;
  wire       _ClusterArray_1_0_O_N_IAct_0_pl;
  wire       _ClusterArray_1_0_O_N_IAct_1_pl;
  wire       _ClusterArray_1_0_O_N_IAct_2_pl;
  wire       _ClusterArray_1_0_O_N_Psum_0_pl;
  wire       _ClusterArray_1_0_O_N_Psum_1_pl;
  wire       _ClusterArray_1_0_O_N_Psum_2_pl;
  wire       _ClusterArray_1_0_O_E_IAct_0_pl;
  wire       _ClusterArray_1_0_O_E_IAct_1_pl;
  wire       _ClusterArray_1_0_O_E_IAct_2_pl;
  wire       _ClusterArray_1_0_O_E_Weight_0_pl;
  wire       _ClusterArray_1_0_O_E_Weight_1_pl;
  wire       _ClusterArray_1_0_O_E_Weight_2_pl;
  wire       _ClusterArray_0_1_O_S_IAct_0_pl;
  wire       _ClusterArray_0_1_O_S_IAct_1_pl;
  wire       _ClusterArray_0_1_O_S_IAct_2_pl;
  wire       _ClusterArray_0_1_O_S_Psum_0_pl;
  wire       _ClusterArray_0_1_O_S_Psum_1_pl;
  wire       _ClusterArray_0_1_O_S_Psum_2_pl;
  wire       _ClusterArray_0_1_O_W_IAct_0_pl;
  wire       _ClusterArray_0_1_O_W_IAct_1_pl;
  wire       _ClusterArray_0_1_O_W_IAct_2_pl;
  wire       _ClusterArray_0_1_O_W_Weight_0_pl;
  wire       _ClusterArray_0_1_O_W_Weight_1_pl;
  wire       _ClusterArray_0_1_O_W_Weight_2_pl;
  wire       _ClusterArray_0_0_O_S_IAct_0_pl;
  wire       _ClusterArray_0_0_O_S_IAct_1_pl;
  wire       _ClusterArray_0_0_O_S_IAct_2_pl;
  wire       _ClusterArray_0_0_O_S_Psum_0_pl;
  wire       _ClusterArray_0_0_O_S_Psum_1_pl;
  wire       _ClusterArray_0_0_O_S_Psum_2_pl;
  wire       _ClusterArray_0_0_O_E_IAct_0_pl;
  wire       _ClusterArray_0_0_O_E_IAct_1_pl;
  wire       _ClusterArray_0_0_O_E_IAct_2_pl;
  wire       _ClusterArray_0_0_O_E_Weight_0_pl;
  wire       _ClusterArray_0_0_O_E_Weight_1_pl;
  wire       _ClusterArray_0_0_O_E_Weight_2_pl;
  Cluster ClusterArray_0_0 (
    .I_N_IAct_0_pl   (1'h0),
    .I_N_IAct_1_pl   (1'h0),
    .I_N_IAct_2_pl   (1'h0),
    .I_N_Psum_0_pl   (1'h0),
    .I_N_Psum_1_pl   (1'h0),
    .I_N_Psum_2_pl   (1'h0),
    .I_S_IAct_0_pl   (_ClusterArray_1_0_O_N_IAct_0_pl),
    .I_S_IAct_1_pl   (_ClusterArray_1_0_O_N_IAct_1_pl),
    .I_S_IAct_2_pl   (_ClusterArray_1_0_O_N_IAct_2_pl),
    .I_S_Psum_0_pl   (_ClusterArray_1_0_O_N_Psum_0_pl),
    .I_S_Psum_1_pl   (_ClusterArray_1_0_O_N_Psum_1_pl),
    .I_S_Psum_2_pl   (_ClusterArray_1_0_O_N_Psum_2_pl),
    .I_W_IAct_0_pl   (1'h0),
    .I_W_IAct_1_pl   (1'h0),
    .I_W_IAct_2_pl   (1'h0),
    .I_W_Weight_0_pl (1'h0),
    .I_W_Weight_1_pl (1'h0),
    .I_W_Weight_2_pl (1'h0),
    .I_E_IAct_0_pl   (_ClusterArray_0_1_O_W_IAct_0_pl),
    .I_E_IAct_1_pl   (_ClusterArray_0_1_O_W_IAct_1_pl),
    .I_E_IAct_2_pl   (_ClusterArray_0_1_O_W_IAct_2_pl),
    .I_E_Weight_0_pl (_ClusterArray_0_1_O_W_Weight_0_pl),
    .I_E_Weight_1_pl (_ClusterArray_0_1_O_W_Weight_1_pl),
    .I_E_Weight_2_pl (_ClusterArray_0_1_O_W_Weight_2_pl),
    .O_N_IAct_0_pl   (/* unused */),
    .O_N_IAct_1_pl   (/* unused */),
    .O_N_IAct_2_pl   (/* unused */),
    .O_N_Psum_0_pl   (/* unused */),
    .O_N_Psum_1_pl   (/* unused */),
    .O_N_Psum_2_pl   (/* unused */),
    .O_S_IAct_0_pl   (_ClusterArray_0_0_O_S_IAct_0_pl),
    .O_S_IAct_1_pl   (_ClusterArray_0_0_O_S_IAct_1_pl),
    .O_S_IAct_2_pl   (_ClusterArray_0_0_O_S_IAct_2_pl),
    .O_S_Psum_0_pl   (_ClusterArray_0_0_O_S_Psum_0_pl),
    .O_S_Psum_1_pl   (_ClusterArray_0_0_O_S_Psum_1_pl),
    .O_S_Psum_2_pl   (_ClusterArray_0_0_O_S_Psum_2_pl),
    .O_W_IAct_0_pl   (/* unused */),
    .O_W_IAct_1_pl   (/* unused */),
    .O_W_IAct_2_pl   (/* unused */),
    .O_W_Weight_0_pl (/* unused */),
    .O_W_Weight_1_pl (/* unused */),
    .O_W_Weight_2_pl (/* unused */),
    .O_E_IAct_0_pl   (_ClusterArray_0_0_O_E_IAct_0_pl),
    .O_E_IAct_1_pl   (_ClusterArray_0_0_O_E_IAct_1_pl),
    .O_E_IAct_2_pl   (_ClusterArray_0_0_O_E_IAct_2_pl),
    .O_E_Weight_0_pl (_ClusterArray_0_0_O_E_Weight_0_pl),
    .O_E_Weight_1_pl (_ClusterArray_0_0_O_E_Weight_1_pl),
    .O_E_Weight_2_pl (_ClusterArray_0_0_O_E_Weight_2_pl),
    .io_Mode         (_ModeScanChain_u_io_out[1:0])
  );
  Cluster ClusterArray_0_1 (
    .I_N_IAct_0_pl   (1'h0),
    .I_N_IAct_1_pl   (1'h0),
    .I_N_IAct_2_pl   (1'h0),
    .I_N_Psum_0_pl   (1'h0),
    .I_N_Psum_1_pl   (1'h0),
    .I_N_Psum_2_pl   (1'h0),
    .I_S_IAct_0_pl   (_ClusterArray_1_1_O_N_IAct_0_pl),
    .I_S_IAct_1_pl   (_ClusterArray_1_1_O_N_IAct_1_pl),
    .I_S_IAct_2_pl   (_ClusterArray_1_1_O_N_IAct_2_pl),
    .I_S_Psum_0_pl   (_ClusterArray_1_1_O_N_Psum_0_pl),
    .I_S_Psum_1_pl   (_ClusterArray_1_1_O_N_Psum_1_pl),
    .I_S_Psum_2_pl   (_ClusterArray_1_1_O_N_Psum_2_pl),
    .I_W_IAct_0_pl   (_ClusterArray_0_0_O_E_IAct_0_pl),
    .I_W_IAct_1_pl   (_ClusterArray_0_0_O_E_IAct_1_pl),
    .I_W_IAct_2_pl   (_ClusterArray_0_0_O_E_IAct_2_pl),
    .I_W_Weight_0_pl (_ClusterArray_0_0_O_E_Weight_0_pl),
    .I_W_Weight_1_pl (_ClusterArray_0_0_O_E_Weight_1_pl),
    .I_W_Weight_2_pl (_ClusterArray_0_0_O_E_Weight_2_pl),
    .I_E_IAct_0_pl   (1'h0),
    .I_E_IAct_1_pl   (1'h0),
    .I_E_IAct_2_pl   (1'h0),
    .I_E_Weight_0_pl (1'h0),
    .I_E_Weight_1_pl (1'h0),
    .I_E_Weight_2_pl (1'h0),
    .O_N_IAct_0_pl   (/* unused */),
    .O_N_IAct_1_pl   (/* unused */),
    .O_N_IAct_2_pl   (/* unused */),
    .O_N_Psum_0_pl   (/* unused */),
    .O_N_Psum_1_pl   (/* unused */),
    .O_N_Psum_2_pl   (/* unused */),
    .O_S_IAct_0_pl   (_ClusterArray_0_1_O_S_IAct_0_pl),
    .O_S_IAct_1_pl   (_ClusterArray_0_1_O_S_IAct_1_pl),
    .O_S_IAct_2_pl   (_ClusterArray_0_1_O_S_IAct_2_pl),
    .O_S_Psum_0_pl   (_ClusterArray_0_1_O_S_Psum_0_pl),
    .O_S_Psum_1_pl   (_ClusterArray_0_1_O_S_Psum_1_pl),
    .O_S_Psum_2_pl   (_ClusterArray_0_1_O_S_Psum_2_pl),
    .O_W_IAct_0_pl   (_ClusterArray_0_1_O_W_IAct_0_pl),
    .O_W_IAct_1_pl   (_ClusterArray_0_1_O_W_IAct_1_pl),
    .O_W_IAct_2_pl   (_ClusterArray_0_1_O_W_IAct_2_pl),
    .O_W_Weight_0_pl (_ClusterArray_0_1_O_W_Weight_0_pl),
    .O_W_Weight_1_pl (_ClusterArray_0_1_O_W_Weight_1_pl),
    .O_W_Weight_2_pl (_ClusterArray_0_1_O_W_Weight_2_pl),
    .O_E_IAct_0_pl   (/* unused */),
    .O_E_IAct_1_pl   (/* unused */),
    .O_E_IAct_2_pl   (/* unused */),
    .O_E_Weight_0_pl (/* unused */),
    .O_E_Weight_1_pl (/* unused */),
    .O_E_Weight_2_pl (/* unused */),
    .io_Mode         (_ModeScanChain_u_io_out[3:2])
  );
  Cluster ClusterArray_1_0 (
    .I_N_IAct_0_pl   (_ClusterArray_0_0_O_S_IAct_0_pl),
    .I_N_IAct_1_pl   (_ClusterArray_0_0_O_S_IAct_1_pl),
    .I_N_IAct_2_pl   (_ClusterArray_0_0_O_S_IAct_2_pl),
    .I_N_Psum_0_pl   (_ClusterArray_0_0_O_S_Psum_0_pl),
    .I_N_Psum_1_pl   (_ClusterArray_0_0_O_S_Psum_1_pl),
    .I_N_Psum_2_pl   (_ClusterArray_0_0_O_S_Psum_2_pl),
    .I_S_IAct_0_pl   (1'h0),
    .I_S_IAct_1_pl   (1'h0),
    .I_S_IAct_2_pl   (1'h0),
    .I_S_Psum_0_pl   (1'h0),
    .I_S_Psum_1_pl   (1'h0),
    .I_S_Psum_2_pl   (1'h0),
    .I_W_IAct_0_pl   (1'h0),
    .I_W_IAct_1_pl   (1'h0),
    .I_W_IAct_2_pl   (1'h0),
    .I_W_Weight_0_pl (1'h0),
    .I_W_Weight_1_pl (1'h0),
    .I_W_Weight_2_pl (1'h0),
    .I_E_IAct_0_pl   (_ClusterArray_1_1_O_W_IAct_0_pl),
    .I_E_IAct_1_pl   (_ClusterArray_1_1_O_W_IAct_1_pl),
    .I_E_IAct_2_pl   (_ClusterArray_1_1_O_W_IAct_2_pl),
    .I_E_Weight_0_pl (_ClusterArray_1_1_O_W_Weight_0_pl),
    .I_E_Weight_1_pl (_ClusterArray_1_1_O_W_Weight_1_pl),
    .I_E_Weight_2_pl (_ClusterArray_1_1_O_W_Weight_2_pl),
    .O_N_IAct_0_pl   (_ClusterArray_1_0_O_N_IAct_0_pl),
    .O_N_IAct_1_pl   (_ClusterArray_1_0_O_N_IAct_1_pl),
    .O_N_IAct_2_pl   (_ClusterArray_1_0_O_N_IAct_2_pl),
    .O_N_Psum_0_pl   (_ClusterArray_1_0_O_N_Psum_0_pl),
    .O_N_Psum_1_pl   (_ClusterArray_1_0_O_N_Psum_1_pl),
    .O_N_Psum_2_pl   (_ClusterArray_1_0_O_N_Psum_2_pl),
    .O_S_IAct_0_pl   (/* unused */),
    .O_S_IAct_1_pl   (/* unused */),
    .O_S_IAct_2_pl   (/* unused */),
    .O_S_Psum_0_pl   (/* unused */),
    .O_S_Psum_1_pl   (/* unused */),
    .O_S_Psum_2_pl   (/* unused */),
    .O_W_IAct_0_pl   (/* unused */),
    .O_W_IAct_1_pl   (/* unused */),
    .O_W_IAct_2_pl   (/* unused */),
    .O_W_Weight_0_pl (/* unused */),
    .O_W_Weight_1_pl (/* unused */),
    .O_W_Weight_2_pl (/* unused */),
    .O_E_IAct_0_pl   (_ClusterArray_1_0_O_E_IAct_0_pl),
    .O_E_IAct_1_pl   (_ClusterArray_1_0_O_E_IAct_1_pl),
    .O_E_IAct_2_pl   (_ClusterArray_1_0_O_E_IAct_2_pl),
    .O_E_Weight_0_pl (_ClusterArray_1_0_O_E_Weight_0_pl),
    .O_E_Weight_1_pl (_ClusterArray_1_0_O_E_Weight_1_pl),
    .O_E_Weight_2_pl (_ClusterArray_1_0_O_E_Weight_2_pl),
    .io_Mode         (_ModeScanChain_u_io_out[5:4])
  );
  Cluster ClusterArray_1_1 (
    .I_N_IAct_0_pl   (_ClusterArray_0_1_O_S_IAct_0_pl),
    .I_N_IAct_1_pl   (_ClusterArray_0_1_O_S_IAct_1_pl),
    .I_N_IAct_2_pl   (_ClusterArray_0_1_O_S_IAct_2_pl),
    .I_N_Psum_0_pl   (_ClusterArray_0_1_O_S_Psum_0_pl),
    .I_N_Psum_1_pl   (_ClusterArray_0_1_O_S_Psum_1_pl),
    .I_N_Psum_2_pl   (_ClusterArray_0_1_O_S_Psum_2_pl),
    .I_S_IAct_0_pl   (1'h0),
    .I_S_IAct_1_pl   (1'h0),
    .I_S_IAct_2_pl   (1'h0),
    .I_S_Psum_0_pl   (1'h0),
    .I_S_Psum_1_pl   (1'h0),
    .I_S_Psum_2_pl   (1'h0),
    .I_W_IAct_0_pl   (_ClusterArray_1_0_O_E_IAct_0_pl),
    .I_W_IAct_1_pl   (_ClusterArray_1_0_O_E_IAct_1_pl),
    .I_W_IAct_2_pl   (_ClusterArray_1_0_O_E_IAct_2_pl),
    .I_W_Weight_0_pl (_ClusterArray_1_0_O_E_Weight_0_pl),
    .I_W_Weight_1_pl (_ClusterArray_1_0_O_E_Weight_1_pl),
    .I_W_Weight_2_pl (_ClusterArray_1_0_O_E_Weight_2_pl),
    .I_E_IAct_0_pl   (1'h0),
    .I_E_IAct_1_pl   (1'h0),
    .I_E_IAct_2_pl   (1'h0),
    .I_E_Weight_0_pl (1'h0),
    .I_E_Weight_1_pl (1'h0),
    .I_E_Weight_2_pl (1'h0),
    .O_N_IAct_0_pl   (_ClusterArray_1_1_O_N_IAct_0_pl),
    .O_N_IAct_1_pl   (_ClusterArray_1_1_O_N_IAct_1_pl),
    .O_N_IAct_2_pl   (_ClusterArray_1_1_O_N_IAct_2_pl),
    .O_N_Psum_0_pl   (_ClusterArray_1_1_O_N_Psum_0_pl),
    .O_N_Psum_1_pl   (_ClusterArray_1_1_O_N_Psum_1_pl),
    .O_N_Psum_2_pl   (_ClusterArray_1_1_O_N_Psum_2_pl),
    .O_S_IAct_0_pl   (/* unused */),
    .O_S_IAct_1_pl   (/* unused */),
    .O_S_IAct_2_pl   (/* unused */),
    .O_S_Psum_0_pl   (/* unused */),
    .O_S_Psum_1_pl   (/* unused */),
    .O_S_Psum_2_pl   (/* unused */),
    .O_W_IAct_0_pl   (_ClusterArray_1_1_O_W_IAct_0_pl),
    .O_W_IAct_1_pl   (_ClusterArray_1_1_O_W_IAct_1_pl),
    .O_W_IAct_2_pl   (_ClusterArray_1_1_O_W_IAct_2_pl),
    .O_W_Weight_0_pl (_ClusterArray_1_1_O_W_Weight_0_pl),
    .O_W_Weight_1_pl (_ClusterArray_1_1_O_W_Weight_1_pl),
    .O_W_Weight_2_pl (_ClusterArray_1_1_O_W_Weight_2_pl),
    .O_E_IAct_0_pl   (/* unused */),
    .O_E_IAct_1_pl   (/* unused */),
    .O_E_IAct_2_pl   (/* unused */),
    .O_E_Weight_0_pl (/* unused */),
    .O_E_Weight_1_pl (/* unused */),
    .O_E_Weight_2_pl (/* unused */),
    .io_Mode         (_ModeScanChain_u_io_out[7:6])
  );
  ScanChain ModeScanChain_u (
    .clock  (clock),
    .reset  (reset),
    .io_in  (io_ModeScanChain),
    .io_out (_ModeScanChain_u_io_out)
  );
endmodule

